document_portal/urls.py
from django.conf.urls import url, include
from django.views.static import serve
from django.contrib import admin
from document_portal import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name="home"),
    url(r'^test/$', views.TestPage.as_view(), name="test"),
    url(r'^thanks/$', views.ThanksPage.as_view(), name="thanks"),
    url(r'^admin/', admin.site.urls),
    url(r'^portal/', include("portal.urls", namespace="portal")),
    url(r'^portal/', include("django.contrib.auth.urls")),
    url(r'^user_page/', include("user_page.urls", namespace="user_page")),
    url(r'^user_page/', include("django.contrib.auth.urls")),
    url(r'^files/', include("files.urls", namespace="files")),
    url(r'^others/', include("others.urls", namespace="others")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from files import views

app_name = 'files'

urlpatterns = [
    url(r'^mydownloads/$',views.downloadlist_view,name='download'),
    url(r'^(?P<uname>\w+)/list/$',views.postlist_view,name='post_list'),
    url(r'^(?P<uname>\w+)/post/new/$',views.newpost,name='post_new'),
    url(r'^post/(?P<pk>\d+)$', views.postdetail_view, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.postupdate_view, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.postdelete_view, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/download/$', views.postdownload, name='downloadpost'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^(?P<uname>\w+)/drafts/$', views.draftlist_view, name='post_draft'),
    url(r'^post/(?P<pk>\d+)/like/$', views.like_post_view, name='like'),
    url(r'^post/(?P<pk>\d+)/unlike/$', views.unlike_post_view, name='unlike'),
    url(r'^post/(?P<pk>\d+)/dislike/$', views.dislike_post_view, name='dislike'),
    url(r'^post/(?P<pk>\d+)/undislike/$', views.undislike_post_view, name='undislike'),
    url(r'^post/(?P<pk>\d+)/likers/$', views.LikersListView, name='likers'),
    url(r'^post/(?P<pk>\d+)/dislikers/$', views.DislikersListView, name='dislikers'),
]

portal/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from portal import views

app_name = 'portal'

urlpatterns = [
    url(r'^login/$', views.Login, name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name ='index.html'), name='logout'),
    url(r'^register/$', views.register, name ='register'),
]

portal/models.py
from django.contrib.auth.models import User

portal/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

portal/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserRegisterForm
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context

########### register here #####################################
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            ######################### mail system ####################################
            #htmly = get_template('app/Email.html')
            #d = { 'username': username }
            #subject, from_email, to = 'welcome', 'your_email@gmail.com', email
            #html_content = htmly.render(d)
            #msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
            #msg.attach_alternative(html_content, "text / html")
            #msg.send()
            ##################################################################
            messages.success(request, f'Your account has been created ! You are now able to log in')
            return redirect('portal:login')
    else:
        form = UserRegisterForm()
    return render(request, 'portal/register.html', {'form': form, 'title':'Sign Up'})

################ login forms###################################################
def Login(request):
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username = username, password = password)
        if user is not None:
            form = login(request, user)
            messages.success(request, f' wecome {username} !!')
            return redirect('user_page:userdashboard', pk=user.id)
        else:
            messages.info(request, f'account done not exit plz sign in')
    form = AuthenticationForm()
    return render(request, 'portal/login.html', {'form':form, 'title':'Log In'})

portal/templates/portal/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{{title}}</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- bootstrap file -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- bootstrap file-->

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



    <!-- message here -->
    {% if messages %}
    {% for message in messages %}
    <script>
    alert("{{ message }}");
    </script>
    {% endfor %}
    {% endif %}
    <!--_______________________________________________-->
</head>

<body>
  <header class="row">
    <!-- navbar-->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="mainNavBar">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'home' %}">Home</a></li>

            {% if user.is_authenticated %}
            <li><a href="{% url 'portal:logout' %}"><span class="glyphicon glyphicon-log-out"></span> &nbsp; Logout</a></li>
            {% else %}
            <li><a href="{% url 'portal:register' %}"><span class="glyphicon glyphicon-user"></span> &nbsp; Signup</a></li>
            <li><a href="{% url 'portal:login' %}"><span class="glyphicon glyphicon-log-in"></span> &nbsp; Login</a></li>
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>
  </header>
  <br/>
  <br>
  <br>

    {% block start %}
    {% endblock %}


    <!-- JS -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

portal/templates/portal/login.html
{% extends "portal/base.html" %}
{% load crispy_forms_tags %}
{% block start %}
<div class="main">
  <section class="signup">
    <div class="container">
        <div class="content-section col-md-8 col-md-offset-2">
          <div class="signup-content">
          <center>
            <form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;" id="signup-form" class="signup-form">
              {% csrf_token %}
              <fieldset class="form-group">
                {{ form|crispy}}
              </fieldset>
              <div class="form-group">
                <input type="submit" name="submit" id="submit" class="form-submit" value="Login"/>
              </div>
              <div class="loginhere">
                Don't have an account ? <a href="{% url 'portal:register' %}" class="loginhere-link">Register here !</a>
              </div>
            </form>
          </center>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock start %}

portal/templates/portal/register.html
{% extends "portal/base.html" %}
{% load crispy_forms_tags %}
{% block start %}
<div class="main">
  <section class="signup">
    <div class="container">
        <div class="content-section col-md-8 col-md-offset-2">
          <div class="signup-content">
          <center>
            <form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;" id="signup-form" class="signup-form">
              {% csrf_token %}
              <fieldset class="form-group">
                {{ form|crispy }}
              </fieldset>
              <div class="form-group">
                  <input type="submit" name="submit" id="submit" class="form-submit" value="Register"/>
              </div>
              <div class="loginhere">
                Already have an account ? <a href="{% url 'portal:login' %}" class="loginhere-link">Login here !</a>
              </div>
            </form>
          </center>
         </div>
       </div>
     </div>
   </section>
 </div>
{% endblock start %}