document_portal/urls.py
from django.conf.urls import url, include
from django.views.static import serve
from django.contrib import admin
from document_portal import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name="home"),
    url(r'^test/$', views.TestPage.as_view(), name="test"),
    url(r'^thanks/$', views.ThanksPage.as_view(), name="thanks"),
    url(r'^admin/', admin.site.urls),
    url(r'^portal/', include("portal.urls", namespace="portal")),
    url(r'^portal/', include("django.contrib.auth.urls")),
    url(r'^user_page/', include("user_page.urls", namespace="user_page")),
    url(r'^user_page/', include("django.contrib.auth.urls")),
    url(r'^files/', include("files.urls", namespace="files")),
    url(r'^others/', include("others.urls", namespace="others")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from files import views

app_name = 'files'

urlpatterns = [
    url(r'^mydownloads/$',views.downloadlist_view,name='download'),
    url(r'^(?P<uname>\w+)/list/$',views.postlist_view,name='post_list'),
    url(r'^(?P<uname>\w+)/post/new/$',views.newpost,name='post_new'),
    url(r'^post/(?P<pk>\d+)$', views.postdetail_view, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.postupdate_view, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.postdelete_view, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/download/$', views.postdownload, name='downloadpost'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^(?P<uname>\w+)/drafts/$', views.draftlist_view, name='post_draft'),
    url(r'^post/(?P<pk>\d+)/like/$', views.like_post_view, name='like'),
    url(r'^post/(?P<pk>\d+)/unlike/$', views.unlike_post_view, name='unlike'),
    url(r'^post/(?P<pk>\d+)/dislike/$', views.dislike_post_view, name='dislike'),
    url(r'^post/(?P<pk>\d+)/undislike/$', views.undislike_post_view, name='undislike'),
    url(r'^post/(?P<pk>\d+)/likers/$', views.LikersListView, name='likers'),
    url(r'^post/(?P<pk>\d+)/dislikers/$', views.DislikersListView, name='dislikers'),
]

others/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from others import views

app_name = 'others'

urlpatterns = [
    url(r'^(?P<uname>\w+)/$',views.dashboard,name='dashboard'),
    url(r'^(?P<uname>\w+)/list/$',views.postlist_view,name='post_list'),
    url(r'^post/(?P<pk>\d+)$', views.postdetail_view, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/download/$', views.postdownload, name='downloadpost'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/like/$', views.like_post_view, name='like'),
    url(r'^post/(?P<pk>\d+)/unlike/$', views.unlike_post_view, name='unlike'),
    url(r'^post/(?P<pk>\d+)/dislike/$', views.dislike_post_view, name='dislike'),
    url(r'^post/(?P<pk>\d+)/undislike/$', views.undislike_post_view, name='undislike'),
    url(r'^post/(?P<pk>\d+)/likers/$', views.LikersListView, name='likers'),
    url(r'^post/(?P<pk>\d+)/dislikers/$', views.DislikersListView, name='dislikers'),
]

user_page/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from user_page import views

app_name = 'user_page'

urlpatterns = [
    url(r'(?P<pk>\d+)/$', views.UserDashboard, name='userdashboard'),
    url(r'(?P<pk>\d+)/updateprofile/$', views.UpdateProfile, name='updateprofile'),
    url(r'(?P<pk>\d+)/myprofile/$', views.MyProfile, name='myprofile'),
    url(r'search/$',views.Search,name='search'),
    url(r'(?P<username>\w+)/followers$', views.FollowersListView, name='followers'),
    url(r'^(?P<username>[-\w]{5,30})/following/$', views.FollowingListView, name='following'),
    url( r'^(?P<username>[-\w]{5,30})/follow/$', views.follow_view, name='follow'),
    url( r'^(?P<username>[-\w]{5,30})/unfollow/$', views.unfollow_view, name='unfollow'),
]

others/models.py
from django.db import models

# Create your models here.

others/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from files.models import DocumentPost, Comment, Like, Dislike, Download
from files.forms import DocumentPostForm, CommentForm

from user_page.models import Connection, UserProfile

from django.contrib.auth.models import User

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from django.forms.models import inlineformset_factory
from django.core.exceptions import PermissionDenied
# Create your views here.

@login_required
def dashboard(request, uname):
    context ={}
    context["uname"] = uname

    if uname is not request.user.username:
        result = Connection.objects.filter(follower__username=request.user.username).filter(following__username=uname)

    context['connected'] = True if result else False

    context["followed_by_uname"] = Connection.objects.filter(follower__username=uname)
    context["who_follows_uname"] = Connection.objects.filter(following__username=uname)
    context["files"] = DocumentPost.objects.filter(published_date__lte=timezone.now()).filter(author__username=uname)
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context['profile'] = UserProfile.objects.get(user=request.user)
            break

    for pr in UserProfile.objects.all():
        if pr.user.username == uname:
            profile = UserProfile.objects.get(user__username=uname)
            context["profile_exist"] = True if profile else False
            context["pro"] = profile
            break

    return render(request, 'others/index.html', context)

@login_required
def postlist_view(request, uname):
    context ={}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context['profile'] = UserProfile.objects.get(user=request.user)
            break

    context["post_list"] = DocumentPost.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    context["uname"] = uname
    return render(request, "others/post_list.html", context)

@login_required
def postdetail_view(request, pk):
    context ={}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context['profile'] = UserProfile.objects.get(user=request.user)
            break

    context["post"] = DocumentPost.objects.get(id=pk)

    liked = Like.objects.filter(user__username=request.user.username).filter(post__pk=pk)
    disliked = Dislike.objects.filter(user__username=request.user.username).filter(post__pk=pk)

    context['liked'] = True if liked else False
    context['disliked'] = True if disliked else False

    context["likes_no"] = Like.objects.filter(post__pk=pk)
    context["dislikes_no"] = Dislike.objects.filter(post__pk=pk)

    downloaded = Download.objects.filter(user__username=request.user.username).filter(post__pk=pk)
    context["downloaded"] = True if downloaded else False

    return render(request, 'others/post_detail.html', context)

@login_required
def postdownload(request, pk):
    try:
        post = get_object_or_404(DocumentPost, id=pk)
        created = Download.objects.get_or_create(post=post, user=request.user)

        if not created:
            messages.warning(request, 'You have already downloaded the post.')

    except DocumentPost.DoesNotExist:
        messages.warning(request, 'post does not exist')

    return redirect('others:post_detail', pk=pk)

@login_required
def add_comment_to_post(request, pk):
    context = {}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context['profile'] = UserProfile.objects.get(user=request.user)
            break

    post = get_object_or_404(DocumentPost, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        context['form'] = form
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('others:post_detail', pk=post.pk)
    else:
        form = CommentForm()
        context['form'] = form

    return render(request, 'others/comment_form.html', context)


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('others:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('others:post_detail', pk=post_pk)


@login_required
def like_post_view(request, pk):
    try:
        post = get_object_or_404(DocumentPost, id=pk)
        created = Like.objects.get_or_create(post=post, user=request.user)

        if not created:
            messages.warning(request, 'You have already liked the post.')

    except DocumentPost.DoesNotExist:
        messages.warning(request, 'post does not exist')

    return redirect('others:post_detail', pk=pk)


@login_required
def unlike_post_view(request, pk):
    try:
        like = Like.objects.get(post__pk = pk, user=request.user)

    except Like.DoesNotExist:
        messages.warning(request, 'You didn\'t like the post.')
    else:
        like.delete()

    return redirect('others:post_detail', pk=pk)

@login_required
def dislike_post_view(request, pk):
    try:
        post = get_object_or_404(DocumentPost, id=pk)
        created = Dislike.objects.get_or_create(post=post, user=request.user)

        if not created:
            messages.warning(request, 'You have already disliked the post.')

    except DocumentPost.DoesNotExist:
        messages.warning(request, 'post does not exist')

    return redirect('others:post_detail', pk=pk)


@login_required
def undislike_post_view(request, pk):
    try:
        dislike = Dislike.objects.get(post__pk = pk, user=request.user)

    except Dislike.DoesNotExist:
        messages.warning(request, 'You didn\'t dislike the post.')
    else:
        dislike.delete()

    return redirect('others:post_detail', pk=pk)


@login_required
def LikersListView(request, pk):
    context = {}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context['profile'] = UserProfile.objects.get(user=request.user)
            break

    post = get_object_or_404(DocumentPost, id=pk)
    context['likers'] = Like.objects.filter(post=post)
    context['title'] = post.title

    return render(request, 'others/likers.html', context)

@login_required
def DislikersListView(request, pk):
    context = {}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context['profile'] = UserProfile.objects.get(user=request.user)
            break

    post = get_object_or_404(DocumentPost, id=pk)
    context['dislikers'] = Dislike.objects.filter(post=post)
    context['title'] = post.title

    return render(request, 'others/dislikers.html', context)

others/templates/others/comment_form.html
{% extends 'user_page/base.html' %}
{% load crispy_forms_tags %}

{% block fine %}
<form class="user" action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}

<fieldset class="form-group">

 {{ form|crispy }}

</fieldset>
<div class="form-group">
  <button class="btn btn-outlint-info btn-primary" type="submit">Post Comment</button>
</div>
</form>

<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

others/templates/others/dislikers.html
{% extends 'user_page/base.html' %}
{% block fine %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{title}}</h1>
</div>
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Disliked by</h1>
</div>
<div class="container">
    {% for disliker in dislikers %}
    <div class="container">
        <div class="card shadow mb-4">
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            {% if disliker.user == user %}
            <h3 class="m-0 text-xs font-weight text-info"><a href="{% url 'user_page:myprofile' pk=user.pk %}"><big>{{ disliker.user.username }}</big></a></h3>
            {% else %}
            <h3 class="m-0 text-xs font-weight text-info"><a href="{% url 'others:dashboard' uname=disliker.user.username %}"><big>{{ disliker.user.username }}</big></a></h3>
            {% endif %}
          </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

others/templates/others/index.html
{% extends 'user_page/base.html' %}
{% block fine %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{uname}}</h1>
</div>
<div class="mb-4">
      {% if connected %}
      <a href="{% url 'user_page:unfollow' username=uname %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-w fa-check-circle fa-sm text-white-50"></i> UnFollow</a>
      {% else%}
      <a href="{% url 'user_page:follow' username=uname %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-w fa-check-circle fa-sm text-white-50"></i> Follow</a>
      {% endif %}

</div>

{% if connected %}
<!-- Content Row -->
<div class="row">

<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><a href="{% url 'user_page:followers' username=uname %}">Followers</a></div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">{{who_follows_uname.count}}</div>
        </div>
        <div class="col-auto"><i class="fas fa-male fa-2x text-gray-300"></i></div>
      </div>
    </div>
  </div>
</div>

<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><a href="{% url 'user_page:following' username=uname %}">Following</a></div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">{{followed_by_uname.count}}</div>
        </div>
        <div class="col-auto"><i class="fas fa-male fa-2x text-gray-300"></i></div>
      </div>
    </div>
  </div>
</div>

<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><a href="{% url 'others:post_list' uname=uname %}">Posts (Files)</a></div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">{{files.count}}</div>
        </div>
        <div class="col-auto"><i class="fas fa-file fa-2x text-gray-300"></i></div>
      </div>
    </div>
  </div>
</div>

</div>

{% if profile_exist %}
<div class="container">
  <div class="col-xl-8 col-lg-7">
    <div class="card shadow mb-4">
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between"><img src="{{pro.image.url}}" alt="profile" width="400px" height="200px"></div>
    <div class="date card-body">
      <h3 class="m-0 font-weight-bold text-dark">{{ pro.first_name|safe|linebreaksbr }} {{pro.last_name|safe|linebreaksbr}}</h3>
      <p>{{ pro.user.username|safe|linebreaksbr }}</p>
      <p>E-mail : {{ pro.user.email|safe|linebreaksbr }} </p>
      <p>Phone No : {{ pro.phone_no|safe|linebreaksbr }}</p>
    </div>
  </div>
</div>
</div>
{% endif %}

{% endif %}
{% endblock %}

others/templates/others/likers.html
{% extends 'user_page/base.html' %}
{% block fine %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{title}}</h1>
</div>
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Liked by</h1>
</div>
<div class="container">
    {% for liker in likers %}
    <div class="container">
        <div class="card shadow mb-4">
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            {% if liker.user == user %}
            <h3 class="m-0 text-xs font-weight text-info"><a href="{% url 'user_page:myprofile' pk=user.pk %}"><big>{{ liker.user.username }}</big></a></h3>
            {% else %}
            <h3 class="m-0 text-xs font-weight text-info"><a href="{% url 'others:dashboard' uname=liker.user.username %}"><big>{{ liker.user.username }}</big></a></h3>
            {% endif %}
          </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

others/templates/others/post_detail.html
{% extends 'user_page/base.html' %}

{% block fine %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{post.author.username}}</h1>
</div>
{% if post.published_date %}
<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><h1 class="m-0 font-weight-bold text-warning text-uppercase">{{ post.title }}</h1></div>
          <div class="h5 mb-0 font-weight-bold text-gray-800"><p class='postcontent m-0 text-secondary'>Description : {{ post.description|safe|linebreaksbr }}</p></div>
          <hr>
          <a class="btn btn-secondary btn-lg text-xs" href="{{post.document.url}}" target = "_blank"><i class="fas fa-w fa-file"></i>  file</a>
          {% if downloaded %}
          <div><p class="m-4">You downloaded this file</p></div>
          {% else %}
          <a class="btn btn-secondary btn-lg text-xs m-4" href="{{post.document.url}}" download><i class="fas fa-w fa-download"></i>  download</a>
          <div><a href="{% url 'others:downloadpost' pk=post.pk %}">Save to mydownloads</a></div>
          {% endif %}
        </div>
      </div>
      <div class="m-4">
        <div class="date postdate text-xs m-0 text-secondary">{{ post.published_date }}</div>
      </div>
    </div>
  </div>
</div>
{% endif %}

<hr>
{% if post.published_date %}

{% if liked %}
<p>You liked this post</p>
<a class="btn btn-info btn-sm" href="{% url 'others:unlike' pk=post.pk %}">
  <i class="fas fa-w fa-thumbs-up"></i>
</a> : <a href="{% url 'others:likers' pk=post.pk %}">{{likes_no.count}}</a>
|
<a class="btn btn-info btn-sm">
  <i class="fas fa-w fa-thumbs-down"></i>
</a> : <a href="{% url 'others:dislikers' pk=post.pk %}">{{dislikes_no.count}}</a>

{% elif disliked %}
<p>You disliked this post</p>
<a class="btn btn-info btn-sm">
  <i class="fas fa-w fa-thumbs-up"></i>
</a> : <a href="{% url 'others:likers' pk=post.pk %}">{{likes_no.count}}</a>
|
<a class="btn btn-info btn-sm" href="{% url 'others:undislike' pk=post.pk %}">
  <i class="fas fa-w fa-thumbs-down"></i>
</a> : <a href="{% url 'others:dislikers' pk=post.pk %}">{{dislikes_no.count}}</a>

{% else %}
<a class="btn btn-info btn-sm" href="{% url 'others:like' pk=post.pk %}">
  <i class="fas fa-w fa-thumbs-up"></i>
</a> : <a href="{% url 'others:likers' pk=post.pk %}">{{likes_no.count}}</a>
|
<a class="btn btn-info btn-sm" href="{% url 'others:dislike' pk=post.pk %}">
  <i class="fas fa-w fa-thumbs-down"></i>
</a> : <a href="{% url 'others:dislikers' pk=post.pk %}">{{dislikes_no.count}}</a>
{% endif %}

<hr>
<a class="btn btn-dark btn-sm" href="{% url 'others:add_comment_to_post' pk=post.pk %}"><i class="fas fa-w fa-plus"></i><span> comment</span></a>
<div class="container mb-4">
  {% for comment in post.comments.all %}
  <br>
  {% if user.is_authenticated or comment.approved_comment %}
  {% if not comment.approved_comment %}
  <a class="btn btn-outline-success" href="{% url 'files:comment_approve' pk=comment.pk %}"><i class="fas fa-w fa-check"></i></a>
  <a class="btn btn-outline-danger" href="{% url 'files:comment_remove' pk=comment.pk %}"><i class="fas fa-w fa-times"></i></a>
  {% endif %}
  <div class="h5 mb-0 font-weight-bold text-gray-800"><p>{{ comment.text|safe|linebreaks }}</p></div>
  <div class="text-sm font-weight-bold text-primary mb-1"><p>by: <strong>{{ comment.author }}</strong></p></div>
  <div class="text-xs text-dark mb-1"><p>{{ comment.created_date }}</p></div>
  {% endif %}
  {% empty %}
  <p>No comments posted.</p>
  {% endfor %}
</div>
{% endif %}
{% endblock %}

others/templates/others/post_list.html
{% extends 'user_page/base.html' %}

{% block fine %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{uname}}</h1>
</div>
<div class="container">
  {% for post in post_list %}
  <div class="container">
    {% if post.author.username == uname %}
    <div class="post row">
      <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h3 class="m-0 font-weight-bold text-primary text-uppercase"><a href="{% url 'others:post_detail' pk=post.pk %}">{{ post.title }}</a></h3>
          </div>
        <div class="date card-body">
          <p>Posted by : {{ post.author.username }}</p>
          <p>Published on : {{ post.published_date}}</p>
          <a href="{% url 'others:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  </div>
  {% endfor %}
</div>

{% endblock %}