document_portal/urls.py
from django.conf.urls import url, include
from django.views.static import serve
from django.contrib import admin
from document_portal import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name="home"),
    url(r'^test/$', views.TestPage.as_view(), name="test"),
    url(r'^thanks/$', views.ThanksPage.as_view(), name="thanks"),
    url(r'^admin/', admin.site.urls),
    url(r'^portal/', include("portal.urls", namespace="portal")),
    url(r'^portal/', include("django.contrib.auth.urls")),
    url(r'^user_page/', include("user_page.urls", namespace="user_page")),
    url(r'^user_page/', include("django.contrib.auth.urls")),
    url(r'^files/', include("files.urls", namespace="files")),
    url(r'^others/', include("others.urls", namespace="others")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from files import views

app_name = 'files'

urlpatterns = [
    url(r'^mydownloads/$',views.downloadlist_view,name='download'),
    url(r'^(?P<uname>\w+)/list/$',views.postlist_view,name='post_list'),
    url(r'^(?P<uname>\w+)/post/new/$',views.newpost,name='post_new'),
    url(r'^post/(?P<pk>\d+)$', views.postdetail_view, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.postupdate_view, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.postdelete_view, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/download/$', views.postdownload, name='downloadpost'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^(?P<uname>\w+)/drafts/$', views.draftlist_view, name='post_draft'),
    url(r'^post/(?P<pk>\d+)/like/$', views.like_post_view, name='like'),
    url(r'^post/(?P<pk>\d+)/unlike/$', views.unlike_post_view, name='unlike'),
    url(r'^post/(?P<pk>\d+)/dislike/$', views.dislike_post_view, name='dislike'),
    url(r'^post/(?P<pk>\d+)/undislike/$', views.undislike_post_view, name='undislike'),
    url(r'^post/(?P<pk>\d+)/likers/$', views.LikersListView, name='likers'),
    url(r'^post/(?P<pk>\d+)/dislikers/$', views.DislikersListView, name='dislikers'),
]

others/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from others import views

app_name = 'others'

urlpatterns = [
    url(r'^(?P<uname>\w+)/$',views.dashboard,name='dashboard'),
    url(r'^(?P<uname>\w+)/list/$',views.postlist_view,name='post_list'),
    url(r'^post/(?P<pk>\d+)$', views.postdetail_view, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/download/$', views.postdownload, name='downloadpost'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/like/$', views.like_post_view, name='like'),
    url(r'^post/(?P<pk>\d+)/unlike/$', views.unlike_post_view, name='unlike'),
    url(r'^post/(?P<pk>\d+)/dislike/$', views.dislike_post_view, name='dislike'),
    url(r'^post/(?P<pk>\d+)/undislike/$', views.undislike_post_view, name='undislike'),
    url(r'^post/(?P<pk>\d+)/likers/$', views.LikersListView, name='likers'),
    url(r'^post/(?P<pk>\d+)/dislikers/$', views.DislikersListView, name='dislikers'),
]

files/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class DocumentPost(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    likes= models.IntegerField(default=0)
    dislikes= models.IntegerField(default=0)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def approve_likes(self):
        return self.likes.filter(approved_like=True)

    def approve_dislikes(self):
        return self.dislikes.filter(approved_like=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('files.DocumentPost', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text


class Like(models.Model):
    post = models.ForeignKey('files.DocumentPost', related_name='liked_post', on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', related_name='liker', on_delete=models.DO_NOTHING)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} : {}'.format(self.user, self.post)

class Dislike(models.Model):
    post = models.ForeignKey('files.DocumentPost', related_name='disliked_post', on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', related_name='disliker', on_delete=models.DO_NOTHING)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} : {}'.format(self.user, self.post)

class Download(models.Model):
    post = models.ForeignKey('files.DocumentPost', on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.DO_NOTHING)

    def __str__(self):
        return '{} : {}'.format(self.user, self.post)

files/forms.py
from django import forms
from .models import DocumentPost, Comment


class DocumentPostForm(forms.ModelForm):

    class Meta:
        model = DocumentPost
        fields = ('title', 'description', 'document',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'description': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

        widgets = {
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }

files/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from .models import DocumentPost, Comment, Like, Dislike, Download
from .forms import DocumentPostForm, CommentForm
from user_page.models import UserProfile

from django.contrib.auth.models import User

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from django.forms.models import inlineformset_factory
from django.core.exceptions import PermissionDenied

@login_required
def downloadlist_view(request):
    context ={}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context['profile'] = UserProfile.objects.get(user=request.user)
            break

    context["downloads"] = Download.objects.filter(user=request.user)
    return render(request, "files/download_list.html", context)

@login_required
def postdownload(request, pk):
    try:
        post = get_object_or_404(DocumentPost, id=pk)
        created = Download.objects.get_or_create(post=post, user=request.user)

        if not created:
            messages.warning(request, 'You have already downloaded the post.')

    except DocumentPost.DoesNotExist:
        messages.warning(request, 'post does not exist')

    return redirect('files:post_detail', pk=pk)

@login_required
def postlist_view(request, uname):
    context ={}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context['profile'] = UserProfile.objects.get(user=request.user)
            break

    context["post_list"] = DocumentPost.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    context["uname"] = uname
    return render(request, "files/post_list.html", context)

@login_required
def newpost(request, uname):
    context = {}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context['profile'] = UserProfile.objects.get(user=request.user)
            break

    if request.method == "POST":
        form = DocumentPostForm(request.POST, request.FILES)
        context['form'] = form
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author = request.user
            obj.save()
            return redirect('user_page:userdashboard', pk=request.user.pk)

    else:
        form = DocumentPostForm()
        context['form'] = form

    return render(request, 'files/post_form.html', context)


@login_required
def postdetail_view(request, pk):
    context ={}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context['profile'] = UserProfile.objects.get(user=request.user)
            break

    context["post"] = DocumentPost.objects.get(id=pk)

    liked = Like.objects.filter(user__username=request.user.username).filter(post__pk=pk)
    disliked = Dislike.objects.filter(user__username=request.user.username).filter(post__pk=pk)

    context['liked'] = True if liked else False
    context['disliked'] = True if disliked else False

    context["likes_no"] = Like.objects.filter(post__pk=pk)
    context["dislikes_no"] = Dislike.objects.filter(post__pk=pk)

    downloaded = Download.objects.filter(user__username=request.user.username).filter(post__pk=pk)
    context["downloaded"] = True if downloaded else False

    return render(request, 'files/post_detail.html', context)


@login_required
def post_publish(request, pk):
    post = get_object_or_404(DocumentPost, id=pk)
    post.publish()
    return redirect('files:post_detail', pk=pk)


@login_required
def postupdate_view(request, pk):
    context = {}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context['profile'] = UserProfile.objects.get(user=request.user)
            break

    obj = get_object_or_404(DocumentPost, id=pk)

    PostForm = DocumentPostForm(request.POST or None, instance = obj)
    context['form'] = PostForm

    if PostForm.is_valid():
        PostForm.save()
        return redirect('files:post_detail', pk=pk)

    return render(request, "files/post_form.html", context)


@login_required
def postdelete_view(request, pk):
    context = {}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context['profile'] = UserProfile.objects.get(user=request.user)
            break

    obj = get_object_or_404(DocumentPost, id = pk)
    context['object'] = obj.title

    if request.method =="POST":
        obj.delete()
        return redirect('files:post_list', uname=request.user.username)

    return render(request, "files/post_delete.html", context)


@login_required
def add_comment_to_post(request, pk):
    context = {}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context['profile'] = UserProfile.objects.get(user=request.user)
            break

    post = get_object_or_404(DocumentPost, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        context['form'] = form
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('files:post_detail', pk=post.pk)
    else:
        form = CommentForm()
        context['form'] = form

    return render(request, 'files/comment_form.html', context)


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('files:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('files:post_detail', pk=post_pk)


@login_required
def draftlist_view(request, uname):
    context ={}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context["profile"] = UserProfile.objects.get(user=request.user)
            break

    context["post_list"] = DocumentPost.objects.filter(published_date__isnull=True).order_by('uploaded_at')
    context["uname"] = uname
    return render(request, "files/post_draft.html", context)


@login_required
def like_post_view(request, pk):
    try:
        post = get_object_or_404(DocumentPost, id=pk)
        created = Like.objects.get_or_create(post=post, user=request.user)

        if not created:
            messages.warning(request, 'You have already liked the post.')

    except DocumentPost.DoesNotExist:
        messages.warning(request, 'post does not exist')

    return redirect('files:post_detail', pk=pk)


@login_required
def unlike_post_view(request, pk):
    try:
        like = Like.objects.get(post__pk = pk, user=request.user)

    except Like.DoesNotExist:
        messages.warning(request, 'You didn\'t like the post.')
    else:
        like.delete()

    return redirect('files:post_detail', pk=pk)

@login_required
def dislike_post_view(request, pk):
    try:
        post = get_object_or_404(DocumentPost, id=pk)
        created = Dislike.objects.get_or_create(post=post, user=request.user)

        if not created:
            messages.warning(request, 'You have already disliked the post.')

    except DocumentPost.DoesNotExist:
        messages.warning(request, 'post does not exist')

    return redirect('files:post_detail', pk=pk)


@login_required
def undislike_post_view(request, pk):
    try:
        dislike = Dislike.objects.get(post__pk = pk, user=request.user)

    except Dislike.DoesNotExist:
        messages.warning(request, 'You didn\'t dislike the post.')
    else:
        dislike.delete()

    return redirect('files:post_detail', pk=pk)

@login_required
def LikersListView(request, pk):
    context = {}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context["profile"] = UserProfile.objects.get(user=request.user)
            break

    post = get_object_or_404(DocumentPost, id=pk)
    context['likers'] = Like.objects.filter(post=post)
    context['title'] = post.title

    return render(request, 'files/likers.html', context)

@login_required
def DislikersListView(request, pk):
    context = {}
    for pr in UserProfile.objects.all():
        if pr.user == request.user:
            context["profile"] = UserProfile.objects.get(user=request.user)
            break

    post = get_object_or_404(DocumentPost, id=pk)
    context['dislikers'] = Dislike.objects.filter(post=post)
    context['title'] = post.title

    return render(request, 'files/dislikers.html', context)

files/templates/files/dislikers.html
{% extends 'user_page/base.html' %}
{% block fine %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{title}}</h1>
</div>
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Disliked by</h1>
</div>
<div class="container">
    {% for disliker in dislikers %}
    <div class="container">
        <div class="card shadow mb-4">
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h3 class="m-0 font-weight-bold text-primary"><a href="{% url 'others:dashboard' uname=disliker.user.username %}">{{ disliker.user.username }}</a></h3>
          </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

files/templates/files/download_list.html
{% extends 'user_page/base.html' %}
{% block fine %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">My Downloads</h1>
</div>
<div class="container">
    {% for download in downloads %}
    <div class="container">
        <div class="card shadow mb-4">
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h3 class="m-0 text-xs font-weight text-info"><a href="{{download.post.document.url}}"><big>{{ download.post.document }} : by {{ download.post.author }}</big></a></h3>
          </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

files/templates/files/likers.html
{% extends 'user_page/base.html' %}
{% block fine %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{title}}</h1>
</div>
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Liked by</h1>
</div>
<div class="container">
    {% for liker in likers %}
    <div class="container">
        <div class="card shadow mb-4">
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h3 class="m-0 font-weight-bold text-primary"><a href="{% url 'others:dashboard' uname=liker.user.username %}">{{ liker.user.username }}</a></h3>
          </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

files/templates/files/post_delete.html
{% extends "user_page/base.html" %}
{% block fine %}
  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
  </form>
{% endblock %}

files/templates/files/post_detail.html
{% extends 'user_page/base.html' %}

{% block fine %}
<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><h1 class="m-0 font-weight-bold text-warning text-uppercase">{{ post.title }}</h1></div>
          <div class="h5 mb-0 font-weight-bold text-gray-800"><p class='postcontent m-0 text-secondary'>Description : {{ post.description|safe|linebreaksbr }}</p></div>
          <hr>
          <a class="btn btn-secondary btn-lg text-xs" href="{{post.document.url}}" target = "_blank"><i class="fas fa-w fa-file"></i>  file</a>
          {% if downloaded %}
          <div><p class="m-4">You downloaded this file</p></div>
          {% else %}
          <a class="btn btn-secondary btn-lg text-xs m-4" href="{{post.document.url}}" download><i class="fas fa-w fa-download"></i>  download</a>
          <div><a href="{% url 'files:downloadpost' pk=post.pk %}">Save to mydownloads</a></div>
          {% endif %}
        </div>
      </div>
      <div class="m-4">

      {% if post.published_date %}
      <div class="date postdate text-xs m-0 text-secondary">
        {{ post.published_date }}
      </div>
      {% else %}
      <a class="btn btn-secondary btn-sm m-0" href="{% url 'files:post_publish' pk=post.pk %}">Post</a>
      {% endif %}
      </div>

    </div>
  </div>
</div>


<hr>
{% if user.is_authenticated %}
<a class="btn btn-outline-success btn-sm" href="{% url 'files:post_edit' pk=post.pk %}"><i class="fas fa-w fa-pencil-alt"></i></a>
<a class="btn btn-outline-danger btn-sm" href="{% url 'files:post_remove' pk=post.pk %}"><i class="fas fa-w fa-trash"></i></a>
{% endif %}

<hr>
{% if post.published_date %}

{% if liked %}
<p>You liked this post</p>
<a class="btn btn-info btn-sm" href="{% url 'files:unlike' pk=post.pk %}">
  <i class="fas fa-w fa-thumbs-up"></i>
</a> : <a href="{% url 'files:likers' pk=post.pk %}">{{likes_no.count}}</a>
|
<a class="btn btn-info btn-sm">
  <i class="fas fa-w fa-thumbs-down"></i>
</a> : <a href="{% url 'files:dislikers' pk=post.pk %}">{{dislikes_no.count}}</a>

{% elif disliked %}
<p>You disliked this post</p>
<a class="btn btn-info btn-sm">
  <i class="fas fa-w fa-thumbs-up"></i>
</a> : <a href="{% url 'files:likers' pk=post.pk %}">{{likes_no.count}}</a>
|
<a class="btn btn-info btn-sm" href="{% url 'files:undislike' pk=post.pk %}">
  <i class="fas fa-w fa-thumbs-down"></i>
</a> : <a href="{% url 'files:dislikers' pk=post.pk %}">{{dislikes_no.count}}</a>

{% else %}
<a class="btn btn-info btn-sm" href="{% url 'files:like' pk=post.pk %}">
  <i class="fas fa-w fa-thumbs-up"></i>
</a> : <a href="{% url 'files:likers' pk=post.pk %}">{{likes_no.count}}</a>
|
<a class="btn btn-info btn-sm" href="{% url 'files:dislike' pk=post.pk %}">
  <i class="fas fa-w fa-thumbs-down"></i>
</a> : <a href="{% url 'files:dislikers' pk=post.pk %}">{{dislikes_no.count}}</a>
{% endif %}



<hr>
<a class="btn btn-dark btn-sm" href="{% url 'files:add_comment_to_post' pk=post.pk %}"><i class="fas fa-w fa-plus"></i><span>   comment</span></a>
<div class="container mb-4">
  {% for comment in post.comments.all %}
  <br>
  {% if user.is_authenticated or comment.approved_comment %}
  {% if not comment.approved_comment %}
  <a class="btn btn-outline-success" href="{% url 'files:comment_approve' pk=comment.pk %}"><i class="fas fa-w fa-check"></i></a>
  <a class="btn btn-outline-danger" href="{% url 'files:comment_remove' pk=comment.pk %}"><i class="fas fa-w fa-times"></i></a>
  {% endif %}
  <div class="h5 mb-0 font-weight-bold text-gray-800"><p>{{ comment.text|safe|linebreaks }}</p></div>
  <div class="text-sm font-weight-bold text-primary mb-1"><p>by: <strong>{{ comment.author }}</strong></p></div>
  <div class="text-xs text-dark mb-1"><p>{{ comment.created_date }}</p></div>
  {% endif %}
  {% empty %}
  <p>No comments posted.</p>
  {% endfor %}
</div>

{% endif %}
{% endblock %}

files/templates/files/post_draft.html
{% extends 'user_page/base.html' %}

{% block fine %}
<div class="container">
  {% for post in post_list %}
  <div class="container">
    {% if post.author.username == uname %}
    <div class="post row">
      <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h3 class="m-0 font-weight-bold text-primary text-uppercase"><a href="{% url 'files:post_detail' pk=post.pk %}">{{ post.title }}</a></h3>
          </div>
          <div class="date card-body">
           <p>Posted by : {{ post.author.username }}</p>
           <p>Uploaded On : {{ post.uploaded_at|date:'d-m-Y' }}</p>
          </div>
        </div>
     </div>
   </div>
   {% endif %}
  </div>
  {% endfor %}
</div>

{% endblock %}

files/templates/files/post_form.html
{% extends 'user_page/base.html' %}
{% load crispy_forms_tags %}

{% block fine %}
<form class="user" action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}{{noodle_form|crispy}}

<fieldset class="form-group">

 {{ form|crispy }}

</fieldset>
<div class="form-group">
  <button class="btn btn-outlint-info btn-primary" type="submit">Save</button>
  <p class="mb-4">Go to drafts and post </p>
</div>
</form>

<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

files/templates/files/post_list.html
{% extends 'user_page/base.html' %}

{% block fine %}
<div class="mb-4">
<a href="{% url 'files:post_draft' uname=uname %}" class="btn btn-dark btn-sm active" role="button" aria-pressed="true"><span> drafts</span></a>
</div>
<div class="container">
  {% for post in post_list %}
  <div class="container">
    {% if post.author.username == uname %}
    <div class="post row">
      <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h3 class="m-0 font-weight-bold text-primary text-uppercase"><a href="{% url 'files:post_detail' pk=post.pk %}">{{ post.title }}</a></h3>
          </div>
        <div class="date card-body">
          <p>Posted by : {{ post.author.username }}</p>
          <p>Published on : {{ post.published_date }}</p>
          <a href="{% url 'files:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  </div>
  {% endfor %}
</div>

{% endblock %}




                        <!-- Area Chart
                        <div class="col-xl-8 col-lg-7">
                            <div class="card shadow mb-4">
                                <!-- Card Header - Dropdown
                                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between ">
                                    <h6 class="m-0 font-weight-bold text-primary"><a href="{% url 'files:post_detail' pk=post.pk %}">{{ post.title }}</a></h6>
                                    <div class="dropdown no-arrow">
                                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                                            aria-labelledby="dropdownMenuLink">
                                            <div class="dropdown-header">Dropdown Header:</div>
                                            <a class="dropdown-item" href="#">Action</a>
                                            <a class="dropdown-item" href="#">Another action</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#">Something else here</a>
                                        </div>
                                    </div>
                                </div>
                                <!-- Card Body
                                <div class="card-body">
                                    <div class="chart-area">
                                        <canvas id="myAreaChart"></canvas>
                                    </div>
                                </div>
                            </div>
                        </div>-->