document_portal/urls.py
from django.conf.urls import url, include
from django.views.static import serve
from django.contrib import admin
from document_portal import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name="home"),
    url(r'^test/$', views.TestPage.as_view(), name="test"),
    url(r'^thanks/$', views.ThanksPage.as_view(), name="thanks"),
    url(r'^admin/', admin.site.urls),
    url(r'^portal/', include("portal.urls", namespace="portal")),
    url(r'^portal/', include("django.contrib.auth.urls")),
    url(r'^user_page/', include("user_page.urls", namespace="user_page")),
    url(r'^user_page/', include("django.contrib.auth.urls")),
    url(r'^files/', include("files.urls", namespace="files")),
    url(r'^others/', include("others.urls", namespace="others")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from files import views

app_name = 'files'

urlpatterns = [
    url(r'^mydownloads/$',views.downloadlist_view,name='download'),
    url(r'^(?P<uname>\w+)/list/$',views.postlist_view,name='post_list'),
    url(r'^(?P<uname>\w+)/post/new/$',views.newpost,name='post_new'),
    url(r'^post/(?P<pk>\d+)$', views.postdetail_view, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.postupdate_view, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.postdelete_view, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/download/$', views.postdownload, name='downloadpost'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^(?P<uname>\w+)/drafts/$', views.draftlist_view, name='post_draft'),
    url(r'^post/(?P<pk>\d+)/like/$', views.like_post_view, name='like'),
    url(r'^post/(?P<pk>\d+)/unlike/$', views.unlike_post_view, name='unlike'),
    url(r'^post/(?P<pk>\d+)/dislike/$', views.dislike_post_view, name='dislike'),
    url(r'^post/(?P<pk>\d+)/undislike/$', views.undislike_post_view, name='undislike'),
    url(r'^post/(?P<pk>\d+)/likers/$', views.LikersListView, name='likers'),
    url(r'^post/(?P<pk>\d+)/dislikers/$', views.DislikersListView, name='dislikers'),
]

others/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from others import views

app_name = 'others'

urlpatterns = [
    url(r'^(?P<uname>\w+)/$',views.dashboard,name='dashboard'),
    url(r'^(?P<uname>\w+)/list/$',views.postlist_view,name='post_list'),
    url(r'^post/(?P<pk>\d+)$', views.postdetail_view, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/download/$', views.postdownload, name='downloadpost'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/like/$', views.like_post_view, name='like'),
    url(r'^post/(?P<pk>\d+)/unlike/$', views.unlike_post_view, name='unlike'),
    url(r'^post/(?P<pk>\d+)/dislike/$', views.dislike_post_view, name='dislike'),
    url(r'^post/(?P<pk>\d+)/undislike/$', views.undislike_post_view, name='undislike'),
    url(r'^post/(?P<pk>\d+)/likers/$', views.LikersListView, name='likers'),
    url(r'^post/(?P<pk>\d+)/dislikers/$', views.DislikersListView, name='dislikers'),
]

portal/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from portal import views

app_name = 'portal'

urlpatterns = [
    url(r'^login/$', views.Login, name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name ='index.html'), name='logout'),
    url(r'^register/$', views.register, name ='register'),
]

user_page/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from user_page import views

app_name = 'user_page'

urlpatterns = [
    url(r'(?P<pk>\d+)/$', views.UserDashboard, name='userdashboard'),
    url(r'(?P<pk>\d+)/updateprofile/$', views.UpdateProfile, name='updateprofile'),
    url(r'(?P<pk>\d+)/myprofile/$', views.MyProfile, name='myprofile'),
    url(r'search/$',views.Search,name='search'),
    url(r'(?P<username>\w+)/followers$', views.FollowersListView, name='followers'),
    url(r'^(?P<username>[-\w]{5,30})/following/$', views.FollowingListView, name='following'),
    url( r'^(?P<username>[-\w]{5,30})/follow/$', views.follow_view, name='follow'),
    url( r'^(?P<username>[-\w]{5,30})/unfollow/$', views.unfollow_view, name='unfollow'),
]

user_page/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from PIL import Image

from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, null=True, blank=True)
    phone_no = models.CharField(max_length = 20, blank=True)
    first_name = models.CharField(max_length = 20, blank=True)
    last_name = models.CharField(max_length = 20, blank=True)
    image = models.ImageField(upload_to='profile_pics/')
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name



class Connection(models.Model):
    follower = models.ForeignKey(User, related_name='follower', on_delete=models.DO_NOTHING)
    following = models.ForeignKey(User, related_name='following', on_delete=models.DO_NOTHING)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} : {}".format(self.follower.username, self.following.username)

user_page/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = models.UserProfile
        fields = ['phone_no', 'first_name', 'last_name', 'image']

class SearchForm(forms.Form):
    searchuser = forms.CharField(label='search for a user', max_length=200)

user_page/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.utils import timezone

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.views import generic
from django.contrib.auth.models import User

from .forms import ProfileUpdateForm,SearchForm
from .models import UserProfile,Connection
from files.models import DocumentPost, Download


# Create your views here.
@login_required
def UserDashboard(request, pk):
    context ={}

    try:
        profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        pass
    else:
        context['profile'] = profile

    context["posts"] = DocumentPost.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    context["followed_by_me"] = Connection.objects.filter(follower=request.user)
    context["who_follows_me"] = Connection.objects.filter(following=request.user)
    context["files"] = DocumentPost.objects.filter(published_date__lte=timezone.now()).filter(author=request.user)
    context["downloads"] = Download.objects.filter(user=request.user)

    return render(request, 'user_page/index.html', context)

@login_required
def MyProfile(request, pk):
    context ={}
    profile_exist = False

    try:
        profile = UserProfile.objects.get(user=request.user)
        if profile:
            profile_exist = True
    except UserProfile.DoesNotExist:
        pass
    else:
        context['profile'] = profile

    user = request.user
    context["user"] = user

    context["followed_by_me"] = Connection.objects.filter(follower=user)
    context["who_follows_me"] = Connection.objects.filter(following=user)
    context["files"] = DocumentPost.objects.filter(published_date__lte=timezone.now()).filter(author=user)
    context["downloads"] = Download.objects.filter(user=user)



    context["profile_exist"] = profile_exist
    if profile_exist:
        context["pro"] = UserProfile.objects.get(user=user)

    return render(request, 'user_page/myprofile.html', context)

@login_required
def UpdateProfile(request, pk):

    profile = False

    if request.method == "POST":
        try:
            userprofile = UserProfile.objects.get(user=request.user)
        except UserProfile.DoesNotExist:
            pass
        else:
            userprofile.delete()

        form = ProfileUpdateForm(request.POST, request.FILES)

        if form.is_valid():

            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            return redirect('user_page:userdashboard', pk=pk)

    else:
        form = ProfileUpdateForm()

    return render(request, 'user_page/updateprofile.html', { 'formset' : form})


@login_required
def Search(request):
    context = {}
    if request.method=="POST":
        form = SearchForm(request.POST)
        context['form'] = form

        if form.is_valid():
            su=form.cleaned_data['searchuser']

            if su==request.user.username:
                return render(request, 'user_page/search_form.html',{'form': form})

            return redirect('others:dashboard', uname=su)

    else:
        form = SearchForm()
        context['form'] = form

    context['users'] = User.objects.filter()
    context['profiles'] = UserProfile.objects.filter()

    return render(request, 'user_page/search_form.html', context)


@login_required
def FollowersListView(request, username):
    context = {}

    try:
        profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        pass
    else:
        context['profile'] = profile

    context["users"] = Connection.objects.filter(following__username=username)
    context['stat'] = 'FOLLOWERS'
    return render(request, 'user_page/connections_list.html', context )


@login_required
def FollowingListView(request, username):
    context = {}

    try:
        profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        pass
    else:
        context['profile'] = profile

    context["users"] = Connection.objects.filter(follower__username=username)
    context['stat'] = 'FOLLOWING'
    return render(request, 'user_page/connections_list.html', context )


@login_required
def follow_view(request, *args, **kwargs):

    try:
        follower = User.objects.get(username=request.user)
        following = User.objects.get(username=kwargs['username'])

    except User.DoesNotExist:
        messages.warning(request, '{} is not a registered user.'.format(kwargs['username']))
        return redirect('user_page:userdashboard', pk=request.user.id)

    if follower == following:
        messages.warning(request, 'You cannot follow yourself.')

    else:
        created = Connection.objects.get_or_create(follower=follower, following=following)

        if (created):
            messages.success(request, 'You have successfully followed {}.'.format(following.username))

        else:
            messages.warning(request, 'You have already followed {}.'.format(following.username))

    return redirect('others:dashboard', uname=following.username)


@login_required
def unfollow_view(request, *args, **kwargs):
    try:
        follower = User.objects.get(username=request.user)
        following = User.objects.get(username=kwargs['username'])

        if follower == following:
            messages.warning(request, 'You cannot unfollow yourself.')

        else:
            unfollow = Connection.objects.get(follower=follower, following=following)
            unfollow.delete()
            messages.success(request, 'You have just unfollowed {}.'.format(following.username))

    except User.DoesNotExist:
        messages.warning(request, '{} is not a registered user.'.format(kwargs['username']))
        return redirect('user_page:userdashboard', pk=request.user.id)
    except Connection.DoesNotExist:
        messages.warning(request, 'You didn\'t follow {0}.'.format(following.username))

    return redirect('others:dashboard', uname=following.username)

user_page/templates/user_page/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{user.username}} - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    {% if messages %}
    {% for message in messages %}
    <script>
    alert("{{ message }}");
    </script>
    {% endfor %}
    {% endif %}

</head>

<body id="page-top">

    {% if user.is_authenticated %}
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <div class="sidebar-brand d-flex align-items-center justify-content-center" >
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">{{user.username}}</div>
            </div>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">Interface</div>

            <li class="nav-item">
              <a class="nav-link collapsed" href="{% url 'user_page:userdashboard' pk=user.id %}"
               data-toggle="collapse" data-target="#collapseTwo"
               aria-expanded="true" aria-controls="collapseTwo">
               <i class="fas fa-fw "></i>
               <span>My Feed</span>
             </a>
            </li>

            <li class="nav-item">
              <a class="nav-link collapsed" href="{% url 'user_page:myprofile' pk=user.id %}"
               data-toggle="collapse" data-target="#collapseTwo"
               aria-expanded="true" aria-controls="collapseTwo">
               <i class="fas fa-fw "></i>
               <span>My Profile</span>
             </a>
            </li>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
              <a class="nav-link collapsed" href="{% url 'user_page:followers' username=user.username %}"
               data-toggle="collapse" data-target="#collapseTwo"
               aria-expanded="true" aria-controls="collapseTwo">
               <i class="fas fa-fw fa-male"></i>
               <span>Followers</span>
              </a>
            </li>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
              <a class="nav-link collapsed" href="{% url 'user_page:following' username=user.username %}"
               data-toggle="collapse" data-target="#collapseTwo"
               aria-expanded="true" aria-controls="collapseTwo">
               <i class="fas fa-fw fa-male"></i>
               <span>Following</span>
              </a>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
             <a class="nav-link collapsed" href="{% url 'files:post_list' uname=user.username %}"
              data-toggle="collapse" data-target="#collapseUtilities"
              aria-expanded="true" aria-controls="collapseUtilities">
              <i class="fas fa-fw fa-file"></i>
              <span>My Posts (Files)</span>
            </a>

            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
             <a class="nav-link collapsed" href="{% url 'files:download' %}"
              data-toggle="collapse" data-target="#collapseUtilities"
              aria-expanded="true" aria-controls="collapseUtilities">
              <i class="fas fa-fw fa-download"></i>
              <span>Downloads</span>
             </a>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'user_page:updateprofile' pk=user.id %}">
                    <i class="fas fa-fw fa-laptop"></i>
                    <span>Update Profile</span>
                </a>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'portal:logout' %}">
                    <i class="fas fa-fw "></i>
                    <span>Logout</span>
                </a>
            </li>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>


                    <div class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                    <div class="input-group">
                      <div class="input-group-append">
                        <a class="form-control bg-dark border-0 small btn btn-primary" href="{% url 'user_page:search' %}" aria-label="Search" aria-describedby="basic-addon2"><i class="fas fa-search fa-sm"></i> Search for other users</a>
                        </div>
                    </div>
                  </div>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                      {% if profile %}
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="{% url 'user_page:updateprofile' pk=user.id %}" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{profile.first_name}} {{profile.last_name}}</span>
                                <img src="{{profile.image.url}}" alt="profile" class="img-profile rounded-circle">
                            </a>
                        </li>
                        {% endif %}

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    {% block fine %}
                    {% endblock %}

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    {% endif %}

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

user_page/templates/user_page/connections_list.html
{% extends 'user_page/base.html' %}

{% block fine %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{stat}}</h1>
</div>
<div class="container">
    {% for us in users %}
    <div class="container">
        {% if stat in 'FOLLOWING' %}
        <div class="card shadow mb-4">
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h3 class="m-0 text-xs font-weight text-info"><a href="{% url 'others:dashboard' uname=us.following.username %}"><big>{{ us.following.username }}</big></a></h3>
          </div>
        </div>
        {% else %}
        <div class="card shadow mb-4">
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h3 class="m-0 text-xs font-weight text-info"><a href="{% url 'others:dashboard' uname=us.follower.username %}"><big>{{ us.follower.username }}</big></a></h3>
          </div>
        </div>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endblock %}

user_page/templates/user_page/index.html
{% extends 'user_page/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block fine %}

<div class="mb-4">
     <h1 class="mb-0 text-primary-800">Welcome {{user.username}} !!!</h1>
</div>

<div class="mb-4">
<a href="{% url 'files:post_new' uname=user.username %}" class="btn btn-warning btn-lg active" role="button" aria-pressed="true"><i class="fas fa-w fa-plus"></i><span> NEW</span></a>
</div>
<div class="mb-4">
<a href="{% url 'files:post_draft' uname=user.username %}" class="btn btn-dark btn-sm active" role="button" aria-pressed="true"><span> drafts</span></a>
</div>

<!-- feed -->

<hr>
<div class="d-sm-flex align-items-center justify-content-between mb-4"><h1 class="h3 mb-0 text-gray-800">Feed</h1></div>
<div class="container">
  {% for post in posts %}
  <div class="container">
    {% for uf in followed_by_me %}
    {% if post.author.username == uf.following.username %}
    <div class="post row">
      <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
          <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h3 class="m-0 font-weight-bold text-primary text-uppercase"><a href="{% url 'others:post_detail' pk=post.pk %}">{{ post.title }}</a></h3>
          </div>
        <div class="date card-body">
          <p>Posted by : {{ post.author.username }}</p>
          <p>Published on : {{ post.published_date|date:"D M Y"}}</p>
          <a href="{% url 'others:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
  </div>
  {% endfor %}
</div>

{% endblock %}

user_page/templates/user_page/myprofile.html
{% extends 'user_page/base.html' %}
{% block fine %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{user.username}}</h1>
</div>
<div class="mb-4">
     <p class="mb-0 text-primary-800">my page</p>
</div>

<!-- Content Row -->
<div class="row">

<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><a href="{% url 'user_page:followers' username=user.username %}">Followers</a></div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">{{who_follows_me.count}}</div>
        </div>
        <div class="col-auto"><i class="fas fa-male fa-2x text-gray-300"></i></div>
      </div>
    </div>
  </div>
</div>


<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-success shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-success text-uppercase mb-1"><a href="{% url 'user_page:following' username=user.username %}">Following</a></div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">{{followed_by_me.count}}</div>
        </div>
        <div class="col-auto"><i class="fas fa-male fa-2x text-gray-300"></i></div>
      </div>
    </div>
  </div>
</div>


<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-info shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-success text-uppercase mb-1"><a href="{% url 'files:post_list' uname=user.username %}">Posts (Files)</a></div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">{{files.count}}</div>
        </div>
        <div class="col-auto"><i class="fas fa-file fa-2x text-gray-300"></i></div>
      </div>
    </div>
  </div>
</div>

<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-warning shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-warning text-uppercase mb-1"><a href="{% url 'files:download' %}">Downloads</a></div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">{{downloads.count}}</div>
        </div>
        <div class="col-auto"><i class="fas fa-download fa-2x text-gray-300"></i></div>
      </div>
    </div>
  </div>
</div>

</div>

{% if profile_exist %}
<div class="container">
  <div class="col-xl-8 col-lg-7">
    <div class="card shadow mb-4">
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between"><img src="{{pro.image.url}}" alt="profile" width="400px" height="200px"></div>
    <div class="date card-body">
      <h3 class="m-0 font-weight-bold text-dark">{{ pro.first_name|safe|linebreaksbr }} {{pro.last_name|safe|linebreaksbr}}</h3>
      <p>{{ pro.user.username|safe|linebreaksbr }}</p>
      <p>E-mail : {{ pro.user.email|safe|linebreaksbr }} </p>
      <p>Phone No : {{ pro.phone_no|safe|linebreaksbr }}</p>
    </div>
  </div>
</div>
</div>
{% endif %}

{% endblock %}